### PR TITLE
Remove platform dependent commands

### LINKED ISSUE #95: build script only supports mac
npm run build currently builds prpl-server & static, but as a windows user the prpl-server script does not work, since it uses commands like:
rm -rf
mv
renamer

none of these commands work on windows. Not really hard to change as a windows users, but perhaps should work out of the box?

### PR DESCRIPTION
**Pull request by Dabolus**
This PR replaces the `rm -rf` and the `mv` commands respectively with the `del-cli` and `move-cli` packages. It also makes some tweaks so that the `build:prpl-server` command can work seamlessly on any platform.

These tweaks will allow Windows users to use the starter kit without manually editing commands in the `package.json`. A future great improvement would be to use Gulp to run the tasks instead, so that we can have more flexibility (and also fix some security issues caused by `renamer` and `replace`). I will try to add some Gulp integration soon , but for now I preferred to fix this issue as soon as possible.

Fixes #95 

PS. Sorry for the dupe, I had some CLA problems with the other email 😅

### CODE REVIEW

**Comment by Dabolus** [comment]
Don't know if it's the same case, but I had this same issue when I tried to run the build command after deleting the `server/` directory. Adding the `--mkdirp` flag to `move-cli` fixed the issue for me.

**Comment by Dabolus** [comment]
About the `move-cli` popularity, strangely I couldn't find any popular package with a good CLI to move files and directories (`move-cli` was actually the most active and updated that i found). This gives me one more reason to just migrate to Gulp.

**Comment by keanulee** [comment]
Hmm, still not working for me even with the flag. Gulp is probably the best way forward.

```
➜  pwa-starter-kit git:(pr/111) ✗ npx move-cli --mkdirp build server/build 
env: node\r: No such file or directory
➜  pwa-starter-kit git:(pr/111) ✗ npx move-cli --mkdirp build server/     
env: node\r: No such file or directory
➜  pwa-starter-kit git:(pr/111) ✗ npx move-cli --mkdirp              
env: node\r: No such file or directory
➜  pwa-starter-kit git:(pr/111) ✗
```

**Comment by Dabolus** [comment]
Ok, I added some Gulp 4 integration and removed the no more used dependencies.
The build command should also **theorically** be faster, as with Gulp `build:static` and `build:prpl-server` are executed in parallel. The build process is basically the same as the one done by the CLI, but with some edits to fit it with our needs (e.g. renaming `node_modules` is handled at build time)

File: .gitignore [hunk 1]
```diff
@@ -3,3 +3,4 @@ node_modules/
 test/integration/screenshots-current
 yarn.lock
 .DS_Store
+.idea
```
Comment (keanulee) [inline .gitignore]: Don't think this is needed.

File: gulpfile.js [hunk 2]
```diff
@@ -0,0 +1,205 @@
...
+gulp.task('build:prpl-server', () => {
+  const autoBasePathedConfig = {
+    ...projectConfig,
+    builds: projectConfig.builds.map((build) => ({
+      ...build,
+      basePath: true,
+    })),
+  };
+  const project = new PolymerProject(autoBasePathedConfig);
+  return Promise.all(autoBasePathedConfig.builds.map((buildConfig) =>
```
Comment (keanulee) [inline gulpfile.js]: Need to output polymer.json so that it can be used by `npm run serve:prpl-server` - similar to https://github.com/Polymer/tools/blob/0cdecd03e7e3709f84fa4f5a52443c19988112be/packages/cli/src/commands/build.ts#L214

**Comment by notwaldorf** [comment]
on it!

File: gulpfile.js [hunk 3]
```diff
@@ -0,0 +1,214 @@
+const gulp = require('gulp');
```
Comment (notwaldorf) [inline gulpfile.js]: Needs license

**Comment by notwaldorf** [comment]
Doesn't work for me (i did a clean `npm install`) on Node 8.2.1 and npm 6.0.0.
screen shot 2018-05-18 at 12 02 51 pm

File: package.json [hunk 4]
```diff
@@ -8,9 +8,9 @@
   "repository": "Polymer/pwa-starter-kit",
   "scripts": {
     "start": "polymer serve",
-    "build": "npm run build:prpl-server && npm run build:static",
-    "build:prpl-server": "polymer build --auto-base-path && rm -rf server/build && mv build server/ && renamer --find node_modules --replace node_assets 'server/build/**' && replace node_modules node_assets server/build -r -s",
-    "build:static": "polymer build",
+    "build": "gulp build",
+    "build:prpl-server": "gulp clean:prpl-server && gulp build:prpl-server",
+    "build:static": "gulp clean:static && gulp build:static",
```
Comment (notwaldorf) [inline package.json]: why does `build:static` need to change? it doesn't have to do any work, so it doesn't need to be built by `gulp`

File: package.json [hunk 5]
```diff
@@ -8,9 +8,9 @@
   "repository": "Polymer/pwa-starter-kit",
   "scripts": {
     "start": "polymer serve",
-    "build": "npm run build:prpl-server && npm run build:static",
-    "build:prpl-server": "polymer build --auto-base-path && rm -rf server/build && mv build server/ && renamer --find node_modules --replace node_assets 'server/build/**' && replace node_modules node_assets server/build -r -s",
-    "build:static": "polymer build",
+    "build": "gulp build",
```
Comment (notwaldorf) [inline package.json]: why does this have to change?

File: gulpfile.js [hunk 6]
```diff
@@ -0,0 +1,214 @@
...
+ * This helper function does basically the same things as the Polymer CLI
+ * `build` command, but it also has some extra options to help us with some
+ * special tasks (e.g. renaming the node_modules output folder).
+ */
+const build = async (options, polymerProject) => {
+  const buildName = options.name || 'default';
+  const buildDirectory = path.join(options.outputDir, buildName);
+  const logPrefix = options.logPrefix || '';
+
+  logger.info(`${logPrefix}(${buildName}) Preparing...`);
```
Comment (notwaldorf) [inline gulpfile.js]: why can't we just `console.log`?

File: gulpfile.js [hunk 7]
```diff
@@ -0,0 +1,214 @@
+const gulp = require('gulp');
+const replace = require('gulp-replace');
+const rename = require('gulp-rename');
+const logger = require('gulplog');
+const path = require('path');
+const fs = require('mz/fs');
```
Comment (notwaldorf) [inline gulpfile.js]: what's wrong with the builtin `fs` package?

File: gulpfile.js [hunk 8]
```diff
@@ -0,0 +1,214 @@
...
+const del = require('del');
+const mergeStream = require('merge-stream');
+const {forkStream, PolymerProject, addServiceWorker, HtmlSplitter, getOptimizeStreams} = require('polymer-build');
```
Comment (notwaldorf) [inline gulpfile.js]: since we already have the `polymer cli` installed, can't we just.......`exec` `polymer build`?

Comment (keanulee) [reply gulpfile.js]: Most of the code is from polymer-cli, but having it here means it can run `build:static` and `build:prpl-server` in parallel (since they won't share the same /build output directory).

File: gulpfile.js (hunk 6 above)
Comment (keanulee) [reply gulpfile.js]: Code from polymer-cli. Does nice formatting stuff, I think.

File: gulpfile.js (hunk 7 above)
Comment (keanulee) [reply gulpfile.js]: Code from polymer-cli

File: package.json (hunk 4 above)
Comment (keanulee) [reply package.json]: I guess technically `build:static` is still functionally equivalent to `polymer build`

File: gulpfile.js (hunk 6 above)
Comment (notwaldorf) [reply gulpfile.js]: i guess my biggest comment is why do we have to redo all the logic `polymer build` does instead of...exec-ing it.

**Comment by Dabolus** [comment]
I moved all the build process to gulp not only to allow parallel building, but also to avoid making the additional post-processing steps after the build. By the way, I agree on the fact that this is pretty much like reinventing the wheel and it can cause a lot of confusion. I'll be back with the edits in a minute

**Comment by keanulee** [comment]
@frankiefu @notwaldorf PTAL

File: package.json [hunk 9]
```diff
@@ -8,8 +8,8 @@
   "repository": "Polymer/pwa-starter-kit",
   "scripts": {
     "start": "polymer serve",
-    "build": "npm run build:prpl-server && npm run build:static",
-    "build:prpl-server": "polymer build --auto-base-path && rm -rf server/build && mv build server/ && renamer --find node_modules --replace node_assets 'server/build/**' && replace node_modules node_assets server/build -r -s",
+    "build": "gulp build",
```
Comment (frankiefu) [inline package.json]: I'd suggest to keep `build` like it was before (`"build": "npm run build:prpl-server && npm run build:static"`) and the `gulpfile.js` will be just for `prpl-server` stuffs.

Btw, thanks for working on the PR @Dabolus!

File: gulpfile.js [hunk 10]
```diff
@@ -0,0 +1,66 @@
...
+gulp.task('clean:prpl-server', () =>
+  del`server/build`);
+
+/**
+ * Builds a static version of the PWA that can be used on any hosting service
+ */
+gulp.task('build:static', (cb) =>
+  // Build the project using Polymer CLI
+  exec('polymer build', cb));
+
```
Comment (frankiefu) [inline gulpfile.js]: Would you mind removing this unused gulp task too? Thanks!

Comment (Dabolus) [reply gulpfile.js]: Sorry, forgot about that one!

**Comment by frankiefu** [comment]
@Dabolus Thanks for all the changes. One last thing, have you ran the script on Windows to make sure the PR really fixes https://github.com/Polymer/pwa-starter-kit/issues/95?

**Comment by Dabolus** [comment]
@frankiefu yep, I tried it on my old laptop (Windows 10, Node v10.0.0, npm v6.0.0). The build was successful and the output files in the server `server/build/` directory were correctly post-processed

**Comment by frankiefu** [comment]
@Dabolus That's awesome! Thanks!
